services:
    os01:
        image: opensearchproject/opensearch:$OS_VERSION
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
            memlock:
                soft: -1
                hard: -1
        container_name: $OS_NODE1
        environment:
            - node.name=$OS_NODE1
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms$OS_JAVA_MEM -Xmx$OS_JAVA_MEM"
            - DISABLE_SECURITY_PLUGIN=true
            - DISABLE_INSTALL_DEMO_CONFIG=true

            # comment this if an OS cluster should be created
            - discovery.type=single-node
            # uncomment this if an OS cluster should be created
            # also add other OS node containers to this compose file
            # - cluster.name=os-arkime-cluster
            # - cluster.initial_cluster_manager_nodes=$OS_NODE1
            # this variable must contain the names (comma-separated) of the OTHER (excluding this container) OS node containers that are part of the cluster
            # - discovery.seed_hosts=$OS_NODE2
        volumes:
            - os01_data:/usr/share/opensearch/data
        networks:
            - arkime-os
    # uncomment to add another OS node container and create a cluster
    # additional some modifications to the "environment" section of the os01 container must be made
    # os02:
    #     image: opensearchproject/opensearch:$OS_VERSION
    #     ulimits:
    #         nofile:
    #             soft: 65535
    #             hard: 65535
    #         memlock:
    #             soft: -1
    #             hard: -1
    #     container_name: $OS_NODE2
    #     environment:
    #         - node.name=$OS_NODE2
    #         - bootstrap.memory_lock=true
    #         - "OPENSEARCH_JAVA_OPTS=-Xms$OS_JAVA_MEM -Xmx$OS_JAVA_MEM"
    #         - DISABLE_SECURITY_PLUGIN=true
    #         - DISABLE_INSTALL_DEMO_CONFIG=true

    #         # cluster settings
    #         - cluster.name=os-arkime-cluster
    #         # this variable must contain the names (comma-separated) of the OTHER (excluding this container) OS node containers that are part of the cluster
    #         - discovery.seed_hosts=$OS_NODE1
    #     volumes:
    #         - os02_data:/usr/share/opensearch/data
    #     networks:
    #         - arkime-os

    arkime:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - $OS_NODE1
            # uncomment and add all OS node container names
            # - $OS_NODE2
        env_file:
            - path: ./env/arkime-compose.env
              # defaults to values defined in Dockerfile
              required: false
        environment:
            - OS_HOST=$OS_NODE1
            - OS_PORT=9200
        ports:
            - $ARKIME_PORT:8005
        volumes:
            - arkime_config:/data/config
            - arkime_logs:/data/logs
            - type: bind
              source: $PCAP_DIR
              target: /data/pcap
        networks:
            - arkime-os

volumes:
    arkime_config:
    arkime_logs:

    os01_data:
    # add a volume foreach OS node container
    # os02_data:


networks:
    arkime-os:
